import Link from "next/link";
import { getRuns, getFleet, computeStats } from "@/lib/data/store";
import { TASKS } from "@/lib/env/tasks";
import Masthead from "@/components/Masthead";
import ModelBehavior from "@/components/ModelBehavior";
import PropensityPanel from "@/components/PropensityPanel";
import FleetHealth from "@/components/FleetHealth";
import { pct, usd, compact, ago } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function Page() {
  const runs = await getRuns();
  const fleet = await getFleet();
  const stats = computeStats(runs);
  const recent = runs.slice(0, 12);

  const simulated = runs.filter((r) => r.source === "simulated").length;
  const allSim = simulated === runs.length && runs.length > 0;

  return (
    <>
      <Masthead tagline="Deterministic, resettable SQL task environments for LLM agents, scored on two axes — task correctness and behavioral trust (propensity) — across the top two models from Anthropic, OpenAI, and Google. Head to demo runs to execute your own agents live." />

      <main className="wrap">
        {allSim && (
          <div className="provenance">
            <span className="pv-tag">PREVIEW DATA</span>
            <span>
              These numbers are generated by{" "}
              <span className="mono">scripts/gen.mjs</span>, not measured from
              model runs, and the pod view below is an illustrative snapshot. To
              replace this with real runs across all six models, add credit to an{" "}
              <span className="mono">OPENROUTER_API_KEY</span> and run{" "}
              <span className="mono">npm run backfill</span> — or execute live
              runs on the{" "}
              <Link href="/demo" className="cta-link">demo</Link> tab. Every run
              is tagged with its provenance; this banner disappears once the
              corpus is real.
            </span>
          </div>
        )}

        <section className="kpis">
          <Kpi label="runs" value={String(stats.total_runs)} sub={`${TASKS.length} environments`} />
          <Kpi label="pass rate" value={pct(stats.pass_rate)} sub="programmatic verifier" />
          <Kpi label="avg trust" value={stats.avg_propensity.toFixed(3)} sub="propensity axis" />
          <Kpi label="flagged" value={pct(stats.propensity_runs ? stats.total_flagged / stats.propensity_runs : 0, 0)} sub={`${stats.total_flagged} behavior flags`} />
          <Kpi label="spend" value={usd(stats.total_cost_usd)} sub={`${compact(stats.total_tokens)} tokens`} />
          <Kpi label="cache hit rate" value={pct(stats.avg_cache_hit_rate)} sub="input served from cache" />
        </section>

        <div className="cta-row">
          <span className="dim">
            Six models across three labs. To run agents yourself and watch live
            results accumulate, open the
          </span>
          <Link href="/demo" className="cta-link">demo runs tab →</Link>
        </div>

        <ModelBehavior stats={stats} />

        <PropensityPanel stats={stats} hint="behavioral trust by model — flag rates separate the labs" />

        <FleetHealth fleet={fleet} />

        {/* RECENT RUNS */}
        <section className="section" id="runs">
          <div className="section-head">
            <h2>recent runs</h2>
            <span className="hint">from the reference corpus &middot; newest first</span>
          </div>
          <div className="card" style={{ padding: 0 }}>
            <table>
              <thead>
                <tr>
                  <th>when</th>
                  <th>environment</th>
                  <th>model</th>
                  <th>result</th>
                  <th className="num">reward</th>
                  <th>trust</th>
                  <th className="num">steps</th>
                  <th className="num">cost</th>
                  <th className="num">cache</th>
                  <th>pod</th>
                </tr>
              </thead>
              <tbody>
                {recent.map((r) => (
                  <tr key={r.id}>
                    <td className="faint mono" style={{ fontSize: 11 }}>{ago(r.started_at)}</td>
                    <td>
                      <Link href={`/runs/${r.id}`} className="mono" style={{ fontSize: 12 }}>{r.task_id}</Link>
                      <span className={`badge ${r.difficulty}`} style={{ marginLeft: 6 }}>{r.difficulty}</span>
                    </td>
                    <td className="mono faint" style={{ fontSize: 11 }}>{r.model}</td>
                    <td>
                      <span className={`badge ${r.status === "passed" ? "pass" : r.status === "failed" ? "fail" : "err"}`}>{r.status}</span>
                    </td>
                    <td className="num">{r.reward.toFixed(3)}</td>
                    <td>
                      {r.propensity ? (
                        r.propensity.flags.length > 0 ? (
                          <span className="badge flag">{r.propensity.score.toFixed(2)} ⚑</span>
                        ) : (
                          <span className="mono faint">{r.propensity.score.toFixed(2)}</span>
                        )
                      ) : (
                        <span className="faint">—</span>
                      )}
                    </td>
                    <td className="num">{r.steps}</td>
                    <td className="num">{usd(r.cost_usd)}</td>
                    <td className="num">{pct(r.cache_hit_rate, 0)}</td>
                    <td className="mono faint" style={{ fontSize: 10 }}>{r.pod}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* ENVIRONMENTS */}
        <section className="section" id="environments">
          <div className="section-head">
            <h2>environments</h2>
            <span className="hint">6 capability tasks + 3 propensity probes &middot; deterministic, programmatic scoring</span>
          </div>
          <div className="grid-3">
            {TASKS.map((t) => (
              <div className="card" key={t.id}>
                <h3 style={{ display: "flex", justifyContent: "space-between", gap: 6 }}>
                  <span className="mono" style={{ fontSize: 12 }}>{t.id}</span>
                  <span style={{ display: "flex", gap: 6 }}>
                    {t.probe && <span className="badge probe">{t.probe.replace(/_/g, " ")}</span>}
                    <span className={`badge ${t.difficulty}`}>{t.difficulty}</span>
                  </span>
                </h3>
                <div style={{ fontWeight: 600, marginBottom: 6 }}>{t.title}</div>
                <div className="dim" style={{ fontSize: 12 }}>{t.prompt}</div>
                <div className="faint mono" style={{ fontSize: 11, marginTop: 10 }}>
                  {t.probe
                    ? `probe: ${t.probe.replace(/_/g, " ")} / axis: behavioral trust`
                    : `kind: ${t.kind} / reward: ${t.kind === "answer" ? "proximity-graded" : "weighted state checks"}`}
                </div>
              </div>
            ))}
          </div>
        </section>

        <footer className="footer">
          <span>podbench is an open source agent evaluation harness. Apache-2.0.</span>
          <span className="mono">policy: claude-opus-4-8 / env: sql-ops / clock: 2026-06-15</span>
        </footer>
      </main>
    </>
  );
}

function Kpi({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="kpi">
      <div className="label">{label}</div>
      <div className="value">{value}</div>
      {sub && <div className="sub">{sub}</div>}
    </div>
  );
}
